blog/urls.py
from django.urls import path
from .views import (
                        laningpage,
                        about_us,
                        custumer,
                        daronchahi,
                        daronchahi2,
                        licens,
                        main,
                        organizationconstruction,
                        policyguidline,
                        process,
                        productAnchor,
                        productLockMandrel,
                        productPacker,
                        products,
                        productSafetyValve,
                        productSSD,
                        productTravel,
                        strategyandgoals,
                        contact_email,
                        liciso1,
                        liciso2,
                        liciso3,
                        liciso4,
                        liciso5,
                        liciso6,
                        hafari,
                        licenseiso,
                        licensentebagh,
                        licensetaeidie,
                        licensesaier,
                        productHanalyse,
                        productHctu,
                        productHfoam,
                        productHmot,
                        productHnitrogengenerator,
                        lavazemBottomNoGo,
                        lavazemFlowCouplin,
                        lavazemFlutedCasing,
                        lavazemFlutedSwedge,
                        lavazemMillOut,
                        lavazemMillOutExtension,
                        lavazemPerforated,
                        lavazemTopNoGo,
                        lavazemTubingCross,
                        lavazemyadaki,
                        p2product
                    )





app_name = 'blog'

urlpatterns = [
    path('', laningpage, name=''),
    path('aboutus/', about_us, name='aboutus'),
    path('custumer/', custumer, name='customer'),
    path('daronchahi/', daronchahi, name='daronchahi'),
    path('daronchahi2/', daronchahi2, name='daronchahi2'),
    path('hafari/', hafari, name='hafari'),
    
    path('licens/', licens, name='licens'),
    path('licenseiso/' , licenseiso, name='licenseiso'),
    path('licensentebagh/', licensentebagh, name='licenseentebagh'),
    path('licensetaeidie/', licensetaeidie, name='licensetaeidie'),
    path('licensesaier/', licensesaier, name='licesnsesaier'),
    
    path('main/', main, name='main'),
    # path('news/', news, name='news'),
    path('organizationconstruction/', organizationconstruction, name='organizationconstruction'),
    path('policyguidline/', policyguidline, name='policyguidline'),
    path('process/', process, name='process'),
    path('productAnchor/', productAnchor, name='productAnchor'),

    path('productHanalyse/', productHanalyse, name='productHanalyse'),
    path('productHctu/', productHctu, name='productHctu'),
    path('productHfoam/', productHfoam, name='prodcutHfoam'),
    path('productHmot/', productHmot, name='prodcutHmot'),
    path('productHnitrogengenerator/', productHnitrogengenerator, name='productHnitrogeangenerator'),

    path('productLockMandrel/', productLockMandrel, name='productLockMandrel'),
    path('productPacker/', productPacker, name='productPacker'),
    path('products/', products, name='products'),
    path('productSafetyValve/', productSafetyValve, name='productSafetyValve'),
    path('productSSD/', productSSD, name='productSSD'),
    path('productTravel/', productTravel, name='productTravel'),
    path('strategyandgoals/', strategyandgoals, name='strategyandgoals'),
    path('liciso1/', liciso1, name='liciso1'),
    path('liciso2/', liciso2, name='liciso2'),
    path('liciso3/', liciso3, name='liciso3'),
    path('liciso4/', liciso4, name='liciso4'),
    path('liciso5/', liciso5, name='liciso5'),
    path('liciso6/', liciso6, name='liciso6'),


    path('lavazemBottomNoGo/', lavazemBottomNoGo, name='lavazemBottomNoGo'),
    path('lavazemFlowCouplin/', lavazemFlowCouplin, name='lavazemFlowCouplin'),
    path('lavazemFlutedCasing/', lavazemFlutedCasing, name='lavazemFlutedCasing'),
    path('lavazemFlutedSwedge/', lavazemFlutedSwedge, name='lavazemFlutedSwedge'),
    path('lavazemMillOut/', lavazemMillOut, name='lavazemMillOut'),
    path('lavazemMillOutExtension/', lavazemMillOutExtension, name='lavazemMillOutExtension'),
    path('lavazemPerforated/', lavazemPerforated, name='lavazemPerforated'),
    path('lavazemTopNoGo/', lavazemTopNoGo, name='lavazemTopNoGo'),
    path('lavazemTubingCross/', lavazemTubingCross, name='lavazemTubingCross'),
    path('lavazemyadaki/', lavazemyadaki, name='lavazemyadaki'),

    path('p2product/', p2product, name='p-2product'),



    path('contact/', contact_email, name='email')
]

demico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
# ]
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone




class Blog(models.Model):
    title        = models.CharField(max_length=100)
    body         = models.TextField(max_length=1000)
    thumbnail    = models.ImageField(null=True, blank=True)
    created      = models.DateTimeField(auto_now_add = True)
    updated      = models.DateTimeField()


    def save(self, *args, **kwargs):
        if not self.created:
            self.created = timezone.now()

        self.updated = timezone.now()
        return super(Blog, self).save(*args, **kwargs)





class Opinion(models.Model):
    full_name           = models.CharField(max_length=50)
    organization_name   = models.CharField(max_length=50, null=True, blank=True,default="وارد نشده")
    responsibility      = models.CharField(max_length=50, null=True, blank=True, default="وارد نشده")
    email               = models.EmailField()
    phone_number        = models.CharField(null=True, blank=True,max_length=12)
    mobile_phone_number = models.CharField(max_length=12)
    description         = models.TextField(max_length = 500)
    time                = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']

    def __str__(self) -> str:
        return self.email

blog/forms.py
from django.forms import ModelForm
from django.forms import widgets
from .models import Opinion
from django import forms



class ContactFrom(ModelForm):
    class Meta:
        model = Opinion
    
        exclude = ['time']

        widgets = {
            'full_name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'الزامی', 'label':'نام کامل'}),
            'organization_name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'اختیاری', 'label':'نام ارگان یا شرکت'}),
            'responsibility': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'اختیاری', 'label':'مسئولیت شما در سازمان'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder': 'الزامی', 'label':'ایمیل'}),
            'phone_number': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'اختیاری', 'label':'شماره تلفن'}),
            'mobile_phone_number': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'الزامی', 'label':'شماره موبایل'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'placeholder': 'الزامی', 'label':'توضیحات'}),
        }
    
    def __init__(self, *args, **kwargs):
        super(ContactFrom, self).__init__(*args, **kwargs)
        self.fields['organization_name'].required = False

blog/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .models import Blog
from .forms import ContactFrom


def laningpage(requset):
    return redirect('blog:main')


def about_us(requset):
    return render(requset, 'blog/aboutus.html')



def custumer(requset):
    return render(requset, 'blog/customer.html')



def daronchahi(requset):
    return render(requset, 'blog/daronchahi.html')



def daronchahi2(requset):
    return render(requset, 'blog/daronchahi2.html')



def licens(requset):
    return render(requset, 'blog/licens.html')


def main(requset):
    news = Blog.objects.all()[:5]
    return render(requset, 'blog/main.html', {'news': news})


def managment(requset):
    return render(requset, 'blog/managment.html')


def managmentNews(requset):
    return render(requset, 'blog/managmentNews.html')


def navtest(requset):
    return render(requset, 'blog/navtest.html')


def news(requset):
    news = Blog.objects.all()[:5]
    return render(requset, 'blog/news.html', {'news': news})


def organizationconstruction(requset):
    return render(requset, 'blog/organizationconstruction.html')


def policyguidline(requset):
    return render(requset, 'blog/policyguidline.html')


def process(requset):
    return render(requset, 'blog/process.html')


def productAnchor(requset):
    return render(requset, 'blog/productAnchor.html')


def productLockMandrel(requset):
    return render(requset, 'blog/productLockMandrel.html')


def productPacker(requset):
    return render(requset, 'blog/productPacker.html')


def products(requset):
    return render(requset, 'blog/products.html')


def productSafetyValve(requset):
    return render(requset, 'blog/productSafetyValve.html')


def productSSD(requset):
    return render(requset, 'blog/productSSD.html')



def productTravel(requset):
    return render(requset, 'blog/productTravel.html')



def strategyandgoals(requset):
    return render(requset, 'blog/strategy&goals.html')



def liciso1(requset):
    return render(requset, 'blog/liciso1.html')


def liciso2(requset):
    return render(requset, 'blog/liciso2.html')


def liciso3(requset):
    return render(requset, 'blog/liciso3.html')


def liciso4(requset):
    return render(requset, 'blog/liciso4.html')


def liciso5(requset):
    return render(requset, 'blog/liciso5.html')


def liciso6(requset):
    return render(requset, 'blog/liciso6.html')


def hafari(requset):
    return render(requset, 'blog/hafari.html')



def licenseiso(requset):
    return render(requset, 'blog/licenseiso.html')

def licensentebagh(requset):
    return render(requset, 'blog/licensentebagh.html')

def licensetaeidie(requset):
    return render(requset, 'blog/licensetaeidie.html')

def licensesaier(requset):
    return render(requset, 'blog/licesnsesaier.html')               




def productHanalyse(request):
    return render(request, 'blog/productHanalyse.html')

def productHctu(request):
    return render(request, 'blog/productHctu.html')

def productHfoam(request):
    return render(request, 'blog/productHfoam.html')



def productHmot(request):
    return render(request, 'blog/productHmot.html')



def productHnitrogengenerator(request):
    return render(request, 'blog/productHnitrogengenerator.html')


def lavazemBottomNoGo(request):
    return render(request, 'blog/lavazemBottomNoGo.html')



def lavazemFlowCouplin(request):
    return render(request, 'blog/lavazemFlowCouplin.html')



def lavazemFlutedCasing(request):
    return render(request, 'blog/lavazemFlutedCasing.html')


def lavazemFlutedSwedge(request):
    return render(request, 'blog/lavazemFlutedSwedge.html')


def lavazemMillOut(request):
    return render(request, 'blog/lavazemMillOut.html')


def lavazemMillOutExtension(request):
    return render(request, 'blog/lavazemMillOutExtension.html')


def lavazemPerforated(request):
    return render(request, 'blog/lavazemPerforated.html')


def lavazemTopNoGo(request):
    return render(request, 'blog/lavazemTopNoGo.html')


def lavazemTubingCross(request):
    return render(request, 'blog/lavazemTubingCross.html')


def lavazemyadaki(request):
    return render(request, 'blog/lavazemyadaki.html')


def p2product(request):
    return render(request, 'blog/p-2product.html')


def contact_email(request):
    if request.method == 'POST':
        form = ContactFrom(request.POST)
        if form.is_valid():
            post = form.save()
            messages.success(request, 'دیدگاه شما ثبت شد')
            return redirect('blog:main')
    
    else:
        form = ContactFrom(request.POST)
    return render(request, 'blog/email.html', {'form': form})

blog/templates/blog/lavazemMillOutExtension.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
لوازم یدکی رشته های تکمیلی درون چاهی
{% endblock %}


{% block content%}






  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="products-daronchahi" class="products-daronchahi margin-adder-product">
<div class="container product-custom-info">
  <div class="row">
    <h3 class="byekanfont mb-4">
      Mill Out Extension
    </h3>
  </div>
  <div class="row">
    
  </div>

  <!-- <div class="splide mt-4 mb-4">
    <div class="splide__track">
      <ul class="splide__list">
        <li class="splide__slide text-center"><img src="./images/products/packer/horz1.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/horz2.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/horz3.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/vert1.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/vert2.png" /></li>
      </ul>
    </div>
  </div> -->

<div class="container">
  <div class="row">
    <div class="col portfolio-box3 shadow">
      <img src="{% static 'images/lavazemyadaki/milloutextension.jpg'%}" />
    </div>
  </div>
</div>


  <div class="row">
      <table class="table mb-4">
        <thead>
          <tr>
            <th scope="col">ردیف</th>
            <th scope="col">SIZE</th>
            <th scope="col">Casing Spec</th>
            <th scope="col">THREAD CONNECTION</th>
            <th scope="col">Material</th>
            <th scope="col">Working Pressure</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>9-5/8” x 7” x 5.5”</td>
            <td>9-5/8” , 43.5-58.4PPF</td>
            <td>5-1/2”,20PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>9-5/8” x 7” x 4.5”</td>
            <td>7” , 29-35PPF</td>
            <td>4-1/2”,13.5PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>9-5/8” x 7” x 3.5”</td>
            <td>7” , 29-35PPF</td>
            <td>3-1/2”,9.2PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">4</th>
            <td>7” x 5” x 4.5”</td>
            <td>7” , 29-35PPF</td>
            <td>4-1/2”,13.5PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>7” x 4.5” x 3.5”</td>
            <td>7” , 32-35PPF</td>
            <td>: 3-1/2”,9.2PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>9-5/8” x 7” x 4.5”</td>
            <td> 7” , 32-35PPF</td>
            <td> : 4-1/2”,15.1PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>10000 Psi</td>
          </tr>
          <tr>
            <th scope="row">7</th>
            <td>7” x 4.5” x 3.5”</td>
            <td>7” , 32-35PPF</td>
            <td>: 3-1/2”,10.2PPF,NEWVAM BOX UP</td>
            <td>4140 or 13Cr</td>
            <td>10000 Psi</td>
          </tr>
        </tbody>
      </table>
  </div>
  <!-- <div class="container"> -->
  <!-- </div> -->
  
</div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->


{% endblock %}

blog/templates/blog/lavazemTopNoGo.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
لوازم یدکی رشته های تکمیلی درون چاهی
{% endblock %}


{% block content%}
  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="products-daronchahi" class="products-daronchahi margin-adder-product">
<div class="container product-custom-info">
  <div class="row">
    <h3 class="byekanfont mb-4">
      TOP NO GO LANDING NIPPLE
    </h3>
  </div>
  <div class="row">
    
  </div>

  <!-- <div class="splide mt-4 mb-4">
    <div class="splide__track">
      <ul class="splide__list">
        <li class="splide__slide text-center"><img src="./images/products/packer/horz1.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/horz2.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/horz3.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/vert1.png" /></li>
        <li class="splide__slide text-center"><img src="./images/products/packer/vert2.png" /></li>
      </ul>
    </div>
  </div> -->

<div class="container">
  <div class="row">
    <div class="col portfolio-box3 shadow">
      <img src="{% static 'images/lavazemyadaki/topNoGo.jpg'%}" />
    </div>
  </div>
</div>

  <div class="row">
      <table class="table mb-4">
        <thead>
          <tr>
            <th scope="col">ردیف</th>
            <th scope="col">SIZE</th>
            <th scope="col">Casing Spec</th>
            <th scope="col">THREAD CONNECTION</th>
            <th scope="col">PROFILE TYPE</th>
            <th scope="col">Material</th>
            <th scope="col">Working Pressure</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>9-5/8” x 7” x 4.5”</td>
            <td>7” , 29-35PPF</td>
            <td>4-1/2”,13.5PPF,NEWVAM B/P</td>
            <td>AF</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>9-5/8” x 7” x 3.5”</td>
            <td>7” , 29-35PPF</td>
            <td>3-1/2”,9.2PPF,NEWVAM B/P</td>
            <td>AF</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>7” x 5” x 4.5”</td>
            <td>7” , 29-35PPF</td>
            <td>4-1/2”,13.5PPF,NEWVAM B/P</td>
            <td>RPT</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">4</th>
            <td>7” x 4.5” x 3.5”</td>
            <td>7” , 32-35PPF</td>
            <td>: 3-1/2”,9.2PPF,NEWVAM B/P</td>
            <td>AF</td>
            <td>4140 or 13Cr</td>
            <td>5000 Psi</td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>9-5/8” x 7” x 4.5”</td>
            <td>7” , 32-35PPF</td>
            <td>4-1/2”,15.1PPF,NEWVAM B/P</td>
            <td>RPT</td>
            <td>4140 or 13Cr</td>
            <td>10000 Psi</td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>9-5/8” x 7” x 4.5”</td>
            <td> 7” , 32-35PPF</td>
            <td> F: 4-1/2”,15.1PPF,NEWVAM B/P</td>
            <td> RPT</td>
            <td>4140 or 13Cr</td>
            <td>10000 Psi</td>
          </tr>
          <tr>
            <th scope="row">7</th>
            <td>7” x 5” x 4.5”</td>
            <td>7” , 32-35PPF</td>
            <td>4-1/2”,15.1PPF,NEWVAM B/P</td>
            <td>AF</td>
            <td>4140 or 13Cr</td>
            <td>10000 Psi</td>
          </tr>
        </tbody>
      </table>
  </div>
  <!-- <div class="container"> -->
  <!-- </div> -->
  
</div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

{% endblock %}

blog/templates/blog/licenseiso.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
گواهینامه های مدیریتی
{% endblock %}


{% block content %}


  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="products-daronchahi" class="products-daronchahi">
  <div class="container" dir="rtl">
    <div class="row">
      <div class="col-sm-12">
        <!-- Section Title -->
        <div class="section-title" data-aos="fade-left">
          <h1>گواهینامه های مدیریتی</h1>
          <div class="divider"></div>
        </div>
      </div>
    </div>
  </div>

<section id="portfolio" class="portfolio">
  <div class="row">
      <a class="col-lg-3 col-md-6" href="{% url 'blog:liciso1' %}">
        <!-- file liciso1 html -->
        <div class="portfolio-box shadow">
          <img src="{% static 'images/license/iso/1.PNG' %}" class="img-portfolio" alt="product 1" title="po1"/>
          <div class="portfolio-info">
            <div class="caption">
              <p>iso 29001 , 2010 نظام مدیریت کیفیت محصولات و خدمات </p>
            </div>
          </div>
        </div>
      </a>
    <a class="col-lg-3 col-md-6" href="{% url 'blog:liciso2' %}">
      <!-- file liciso2 html -->
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/iso/2.PNG' %}" class="img-portfolio" alt="product 2" title="po2"/>
        <div class="portfolio-info">
          <div class="caption">
            <p>iso 45001,2018 نظام مدیریت ایمنی و بهداشت </p>
          </div>
        </div>
      </div>
    </a>
    <a class="col-lg-3 col-md-6" href="{% url 'blog:liciso3' %}">
      <!-- file liciso3 html -->
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/iso/3.PNG' %}" class="img-portfolio" alt="product 2" title="po2"/>
        <div class="portfolio-info">
          <div class="caption">
            <p>ISO 9001 , 2015 نظام مدیریت کیفیت </p>
          </div>
        </div>
      </div>
    </a>
    <a class="col-lg-3 col-md-6" href="{ url 'blog:liciso4' }">
      <!-- file liciso4 html -->
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/iso/4.PNG' %}" class="img-portfolio" alt="product 2" title="po2"/>
        <div class="portfolio-info">
          <div class="caption">
            <p>ISO 50001 , 2018 نظام مدیریت انرژی </p>
          </div>
        </div>
      </div>
    </a>
    <a class="col-lg-3 col-md-6" href="{% url 'blog:liciso5' %}">
      <!-- file liciso 5 html -->
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/iso/5.PNG' %}" class="img-portfolio" alt="product 2" title="po2"/>
        <div class="portfolio-info">
          <div class="caption">
            <p>ISO 31000 , 2018 نظام مدیریت یسک</p>
          </div>
        </div>
      </div>
    </a>
    <a class="col-lg-3 col-md-6" href="{% url 'blog:liciso6' %}">
      <!-- file liciso 6 html -->
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/iso/6.PNG' %}" class="img-portfolio" alt="product 2" title="po2"/>
        <div class="portfolio-info">
          <div class="caption">
            <p>ISO 14001 , 2015 نظام مدیریت محیط زیست </p>
          </div>
        </div>
      </div>
    </a>
</section>
</div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

{% endblock %}

blog/templates/blog/licensentebagh.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
گواهینامه های انطباق
{% endblock %}


{% block content %}




  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="products-daronchahi" class="products-daronchahi">
  <div class="container" dir="rtl">
    <div class="row">
      <div class="col-sm-12">
        <!-- Section Title -->
        <div class="section-title" data-aos="fade-left">
          <h1> گواهینامه های انطباق محصول</h1>
          <div class="divider"></div>
        </div>
      </div>
    </div>
  </div>

<section id="portfolio" class="portfolio">
  <div class="row justify-content-center">
    
    <a class="col-lg-3 col-md-12" href="{% url 'blog:licens' %}">
    <div >
      <div class="portfolio-box shadow">
        <img src="{% static 'images/license/lic2.png' %}" class="img-portfolio" alt="product 1" title="po1"/>
        <div class="portfolio-info">
          <div class="caption">
            گواهینامه انطباق
            <!-- file license html -->
          </div>
        </div>
      </div>
    </div>
    </a>
  
</section>
</div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

{% endblock %}

blog/templates/blog/licesnsesaier.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
سایر گواهینامه ها
{% endblock %}


{% block content %}



  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
  <section id="products-daronchahi" class="products-daronchahi">
    <div class="container" dir="rtl">
      <div class="row">
        <div class="col-sm-12">
          <!-- Section Title -->
          <div class="section-title" data-aos="fade-left">
            <h1>سایر گواهینامه ها</h1>
            <div class="divider"></div>
          </div>
        </div>
      </div>
    </div>

    <section id="portfolio" class="portfolio">
      <div class="row">

      </div>
    </section>
    </div>
  </section>


  <!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
{% endblock %}

blog/templates/blog/liciso6.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
گواهینامه
{% endblock %}


{% block content %}



  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="orgconst" class="orgconst">
  <div class="container text-center">
    <img src="{% static 'images/license/iso/6.PNG' %}" class="orgmang-custom-managment" />
  </div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
{% endblock %}

blog/templates/blog/organizationconstruction.html
{% extends 'base.html' %}
{% load static %}

{% load change %} 


{% block title %}
سازمان
{% endblock %}


{% block content %}





  <!-- ///////////////////////////////////// description about the product \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
<section id="orgconst" class="orgconst">
  <div class="container">
    <img src="{% static 'images/managment/orgmanag.png' %}" class="orgmang-custom-managment" />
  </div>
</section>


<!-- //////////////////////////////////ABOUT US FINISHED\\\\\\\\\\\\\\\\\\\\\\\\\\ -->


{% endblock %}